package com.web.soulyogaadmin.entity;
// Generated 2017-6-22 13:56:57 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Courseattendance generated by hbm2java
 */
public class Courseattendance implements java.io.Serializable {

	private Integer id;
	private int memberId;
	private int courseReservationId;
	private int productPurchaseId;
	private Date checkInTime;
	private Date checkOutTime;
	private Date createdTime;
	private Date modifiedTime;
	private int state;

	public Courseattendance() {
	}

	public Courseattendance(int memberId, int courseReservationId, int productPurchaseId, Date createdTime, int state) {
		this.memberId = memberId;
		this.courseReservationId = courseReservationId;
		this.productPurchaseId = productPurchaseId;
		this.createdTime = createdTime;
		this.state = state;
	}

	public Courseattendance(int memberId, int courseReservationId, int productPurchaseId, Date checkInTime,
			Date checkOutTime, Date createdTime, Date modifiedTime, int state) {
		this.memberId = memberId;
		this.courseReservationId = courseReservationId;
		this.productPurchaseId = productPurchaseId;
		this.checkInTime = checkInTime;
		this.checkOutTime = checkOutTime;
		this.createdTime = createdTime;
		this.modifiedTime = modifiedTime;
		this.state = state;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	public int getCourseReservationId() {
		return this.courseReservationId;
	}

	public void setCourseReservationId(int courseReservationId) {
		this.courseReservationId = courseReservationId;
	}

	public int getProductPurchaseId() {
		return this.productPurchaseId;
	}

	public void setProductPurchaseId(int productPurchaseId) {
		this.productPurchaseId = productPurchaseId;
	}

	public Date getCheckInTime() {
		return this.checkInTime;
	}

	public void setCheckInTime(Date checkInTime) {
		this.checkInTime = checkInTime;
	}

	public Date getCheckOutTime() {
		return this.checkOutTime;
	}

	public void setCheckOutTime(Date checkOutTime) {
		this.checkOutTime = checkOutTime;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

}
