package com.web.soulyogaadmin.entity;
// Generated 2017-6-22 13:56:57 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Coursereservation generated by hbm2java
 */
public class Coursereservation implements java.io.Serializable {

	private Integer id;
	private int memberId;
	private int courseScheduleId;
	private String teacherName;
	private String courseName;
	private String classroomNo;
	private String yogaClubName;
	private Date scheduleDate;
	private String startTime;
	private String endTime;
	private String yogaCushionNo;
	private int status;
	private Date createdTime;
	private Date modifiedTime;
	private int state;

	public Coursereservation() {
	}

	public Coursereservation(int memberId, int courseScheduleId, String teacherName, String courseName,
			String classroomNo, String yogaClubName, Date scheduleDate, String startTime, String endTime,
			String yogaCushionNo, int status, Date createdTime, int state) {
		this.memberId = memberId;
		this.courseScheduleId = courseScheduleId;
		this.teacherName = teacherName;
		this.courseName = courseName;
		this.classroomNo = classroomNo;
		this.yogaClubName = yogaClubName;
		this.scheduleDate = scheduleDate;
		this.startTime = startTime;
		this.endTime = endTime;
		this.yogaCushionNo = yogaCushionNo;
		this.status = status;
		this.createdTime = createdTime;
		this.state = state;
	}

	public Coursereservation(int memberId, int courseScheduleId, String teacherName, String courseName,
			String classroomNo, String yogaClubName, Date scheduleDate, String startTime, String endTime,
			String yogaCushionNo, int status, Date createdTime, Date modifiedTime, int state) {
		this.memberId = memberId;
		this.courseScheduleId = courseScheduleId;
		this.teacherName = teacherName;
		this.courseName = courseName;
		this.classroomNo = classroomNo;
		this.yogaClubName = yogaClubName;
		this.scheduleDate = scheduleDate;
		this.startTime = startTime;
		this.endTime = endTime;
		this.yogaCushionNo = yogaCushionNo;
		this.status = status;
		this.createdTime = createdTime;
		this.modifiedTime = modifiedTime;
		this.state = state;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	public int getCourseScheduleId() {
		return this.courseScheduleId;
	}

	public void setCourseScheduleId(int courseScheduleId) {
		this.courseScheduleId = courseScheduleId;
	}

	public String getTeacherName() {
		return this.teacherName;
	}

	public void setTeacherName(String teacherName) {
		this.teacherName = teacherName;
	}

	public String getCourseName() {
		return this.courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	public String getClassroomNo() {
		return this.classroomNo;
	}

	public void setClassroomNo(String classroomNo) {
		this.classroomNo = classroomNo;
	}

	public String getYogaClubName() {
		return this.yogaClubName;
	}

	public void setYogaClubName(String yogaClubName) {
		this.yogaClubName = yogaClubName;
	}

	public Date getScheduleDate() {
		return this.scheduleDate;
	}

	public void setScheduleDate(Date scheduleDate) {
		this.scheduleDate = scheduleDate;
	}

	public String getStartTime() {
		return this.startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return this.endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getYogaCushionNo() {
		return this.yogaCushionNo;
	}

	public void setYogaCushionNo(String yogaCushionNo) {
		this.yogaCushionNo = yogaCushionNo;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@Override
	public String toString() {
		return "Coursereservation [id=" + id + ", memberId=" + memberId + ", courseScheduleId=" + courseScheduleId
				+ ", teacherName=" + teacherName + ", courseName=" + courseName + ", classroomNo=" + classroomNo
				+ ", yogaClubName=" + yogaClubName + ", scheduleDate=" + scheduleDate + ", startTime=" + startTime
				+ ", endTime=" + endTime + ", yogaCushionNo=" + yogaCushionNo + ", status=" + status + ", createdTime="
				+ createdTime + ", modifiedTime=" + modifiedTime + ", state=" + state + "]";
	}

}
