package com.web.soulyogaadmin.entity;
// Generated 2017-6-22 13:56:57 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private Integer id;
	private String name;
	private int cardCategoryId;
	private long price;
	private int activationCategory;
	private String usingStartTime;
	private String usingEndTime;
	private Integer count;
	private String usingRestriction;
	private Date createdTime;
	private Date modifiedTime;
	private int state;

	public Product() {
	}

	public Product(String name, int cardCategoryId, long price, int activationCategory, String usingStartTime,
			String usingEndTime, Date createdTime, int state) {
		this.name = name;
		this.cardCategoryId = cardCategoryId;
		this.price = price;
		this.activationCategory = activationCategory;
		this.usingStartTime = usingStartTime;
		this.usingEndTime = usingEndTime;
		this.createdTime = createdTime;
		this.state = state;
	}

	public Product(String name, int cardCategoryId, long price, int activationCategory, String usingStartTime,
			String usingEndTime, Integer count, String usingRestriction, Date createdTime, Date modifiedTime,
			int state) {
		this.name = name;
		this.cardCategoryId = cardCategoryId;
		this.price = price;
		this.activationCategory = activationCategory;
		this.usingStartTime = usingStartTime;
		this.usingEndTime = usingEndTime;
		this.count = count;
		this.usingRestriction = usingRestriction;
		this.createdTime = createdTime;
		this.modifiedTime = modifiedTime;
		this.state = state;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getCardCategoryId() {
		return this.cardCategoryId;
	}

	public void setCardCategoryId(int cardCategoryId) {
		this.cardCategoryId = cardCategoryId;
	}

	public long getPrice() {
		return this.price;
	}

	public void setPrice(long price) {
		this.price = price;
	}

	public int getActivationCategory() {
		return this.activationCategory;
	}

	public void setActivationCategory(int activationCategory) {
		this.activationCategory = activationCategory;
	}

	public String getUsingStartTime() {
		return this.usingStartTime;
	}

	public void setUsingStartTime(String usingStartTime) {
		this.usingStartTime = usingStartTime;
	}

	public String getUsingEndTime() {
		return this.usingEndTime;
	}

	public void setUsingEndTime(String usingEndTime) {
		this.usingEndTime = usingEndTime;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public String getUsingRestriction() {
		return this.usingRestriction;
	}

	public void setUsingRestriction(String usingRestriction) {
		this.usingRestriction = usingRestriction;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

}
